spring:
  application:
    name: projectD
  config:
    import: optional:configserver:http://localhost:8888  # Подключаем Config Server
  cloud:
    config:
      fail-fast: true  # Если Config Server недоступен, приложение сразу завершится с ошибкой
      retry:
        initial-interval: 2000  # Начальная задержка перед повторной попыткой (2 сек)
        max-interval: 10000  # Максимальный интервал между попытками (10 сек)
        max-attempts: 6  # Количество попыток

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Подключаем Eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh  # Доступ к эндпоинтам Spring Actuator
